---
- name: install apache2 on ubuntu server
  hosts: ubuntu
  become: true
  tasks:
   - name: install on ubuntu
     apt:
      name: apache2
      state: present

   - name: start apache2
     service:
       name: apache2
       state: started
