---
- name: this playbook to uninstall packages
  hosts: web
  become: true
  tasks:
   - name: stop httpd service
     service:
      name: httpd
      state: stopped
   - name: uninstall package
     yum:
       name: httpd
       state: removed
   
     

